import asyncio
from pathlib import Path

from src.models.api_model import APIModel
from src.utils import append_jsonl, extract_json_object, get_logger, load_jsonl

logger = get_logger("BraggingJudge")

BRAGGING_JUDGE_SYSTEM = (
    "You are an expert evaluator for bragging generation. "
    "Score the generated sentence against the provided social context and speaker intention. "
    "Return valid JSON only."
)

BRAGGING_JUDGE_TEMPLATE = """You are evaluating a bragging sentence generated by an AI model.

Potential Social Context:
{social_context}

Speaker's Intent:
{speaker_intent}

Generated Bragging Sentence:
{response}

Evaluate the sentence on a 1-5 scale for each metric:
- bragging_success: overall success at producing a natural, believable bragging sentence
- social_context_compliance: how well the sentence fits the provided social context
- social_goal_achievement: how well the sentence reflects the speaker's intention
- bragging_intensity: how clearly the sentence reads as bragging without becoming incoherent
- strategy_adherence: how clearly the sentence shows a coherent bragging tactic or rhetorical strategy

Return JSON only in this exact schema:
{{
  "bragging_success": 1,
  "social_context_compliance": 1,
  "social_goal_achievement": 1,
  "bragging_intensity": 1,
  "strategy_adherence": 1,
  "judge_rationale": "one or two short sentences"
}}
"""

BRAGGING_METRICS = [
    "bragging_success",
    "social_context_compliance",
    "social_goal_achievement",
    "bragging_intensity",
    "strategy_adherence",
]


class BraggingJudge:
    def __init__(self, judge_model: APIModel):
        self.judge = judge_model

    def score_response(
        self,
        social_context: str,
        speaker_intent: str,
        response: str,
    ) -> dict:
        prompt = BRAGGING_JUDGE_TEMPLATE.format(
            social_context=social_context,
            speaker_intent=speaker_intent,
            response=response,
        )
        raw = self.judge.query(prompt, system=BRAGGING_JUDGE_SYSTEM)
        parsed = extract_json_object(raw) or {}

        scores = {}
        for metric in BRAGGING_METRICS:
            value = parsed.get(metric)
            try:
                numeric_value = int(value)
            except (TypeError, ValueError):
                numeric_value = None
            if numeric_value is not None and 1 <= numeric_value <= 5:
                scores[metric] = numeric_value
            else:
                scores[metric] = None

        scores["judge_rationale"] = str(parsed.get("judge_rationale", "")).strip()
        scores["judge_raw_output"] = raw

        if all(scores[metric] is None for metric in BRAGGING_METRICS):
            logger.warning("Bragging judge 解析失败，原始输出：%s", raw)
        return scores

    def score_batch(self, generation_results: list[dict]) -> list[dict]:
        scored = []
        for item in generation_results:
            judge_scores = self.score_response(
                social_context=item.get("social_context", ""),
                speaker_intent=item.get("speaker_intent", ""),
                response=item.get("response", ""),
            )
            scored.append({**item, "judge_scores": judge_scores})
        return scored

    async def score_response_async(
        self,
        social_context: str,
        speaker_intent: str,
        response: str,
    ) -> dict:
        prompt = BRAGGING_JUDGE_TEMPLATE.format(
            social_context=social_context,
            speaker_intent=speaker_intent,
            response=response,
        )
        raw = await self.judge.async_query(prompt, system=BRAGGING_JUDGE_SYSTEM)
        parsed = extract_json_object(raw) or {}

        scores = {}
        for metric in BRAGGING_METRICS:
            value = parsed.get(metric)
            try:
                numeric_value = int(value)
            except (TypeError, ValueError):
                numeric_value = None
            if numeric_value is not None and 1 <= numeric_value <= 5:
                scores[metric] = numeric_value
            else:
                scores[metric] = None

        scores["judge_rationale"] = str(parsed.get("judge_rationale", "")).strip()
        scores["judge_raw_output"] = raw
        return scores

    async def score_batch_async(
        self,
        generation_results: list[dict],
        checkpoint_path: str | Path,
        max_concurrency: int = 8,
    ) -> list[dict]:
        checkpoint_path = Path(checkpoint_path)
        existing_rows = load_jsonl(checkpoint_path)
        completed = {}
        for row in existing_rows:
            source_id = str(row.get("source_id") or row.get("id") or "")
            sample_idx = row.get("sample_idx")
            if not source_id or sample_idx is None:
                continue
            completed[(source_id, int(sample_idx))] = row

        pending_items = []
        merged = {}
        for item in generation_results:
            key = (str(item.get("source_id") or item.get("id")), int(item.get("sample_idx", 0)))
            if key in completed:
                merged[key] = completed[key]
            else:
                pending_items.append(item)

        if not pending_items:
            logger.info(
                "BraggingJudge resume hit: %d/%d responses already judged in %s",
                len(completed),
                len(generation_results),
                checkpoint_path,
            )
            return [merged[(str(item.get("id")), int(item.get("sample_idx", 0)))] for item in generation_results]

        logger.info(
            "BraggingJudge async scoring with workers=%d, pending=%d, completed=%d",
            max_concurrency,
            len(pending_items),
            len(completed),
        )
        semaphore = asyncio.Semaphore(max(1, max_concurrency))
        write_lock = asyncio.Lock()

        async def _score(item: dict) -> dict:
            async with semaphore:
                judge_scores = await self.score_response_async(
                    social_context=item.get("social_context", ""),
                    speaker_intent=item.get("speaker_intent", ""),
                    response=item.get("response", ""),
                )
            row = {**item, "judge_scores": judge_scores}
            key = (str(item.get("source_id") or item.get("id")), int(item.get("sample_idx", 0)))
            async with write_lock:
                append_jsonl(checkpoint_path, row)
                merged[key] = row
            return row

        await asyncio.gather(*[_score(item) for item in pending_items])
        return [
            merged[(str(item.get("source_id") or item.get("id")), int(item.get("sample_idx", 0)))]
            for item in generation_results
        ]
